"""field position in user

Revision ID: ce2d288288b2
Revises: 9d92646a7742
Create Date: 2020-05-27 23:41:23.084498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce2d288288b2'
down_revision = '9d92646a7742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('position', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'position')
    # ### end Alembic commands ###
