"""teposition table

Revision ID: eb045fe87453
Revises: b593c1be9903
Create Date: 2020-05-28 15:28:47.915636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb045fe87453'
down_revision = 'b593c1be9903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('users', sa.Column('position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'position', ['position_id'], ['id'])
    op.drop_column('users', 'position')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('position', sa.VARCHAR(length=120), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'position_id')
    op.drop_table('position')
    # ### end Alembic commands ###
